# Generated by Django 4.2 on 2023-05-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labeling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labeledimage",
            name="trained",
            field=models.BooleanField(default=False),
        ),
    ]
